name: Build and Deploy to GitHub Pages
on:
  push:
    branches: [master]
jobs:
  build:
    name: build-and-deploy
#     runs-on: ubuntu-lates 
    runs-on: self-hosted
    steps:
    - name: Checkout
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Moving build to artifacts directory
      run: |
        chmod +x ./scripts/moveFiles.sh
        ./scripts/moveFiles.sh
