name: Build and Deploy to GitHub Pages
on:
  push:
    branches: [master]
jobs:
  build:
    name: build-and-deploy
#     runs-on: ubuntu-lates 
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
     run: |
       chmod +x ./.github/scripts/https.sh
       ./.github/scripts/https.sh    
