name: https-legendsandmasters.nl
# on:
#   pull_request:
#     branches:
#       - 'master'
#   push:
#     branches:
#       - 'master' 

on:
  schedule: 
  - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Test URL
      run: |
        uname -a
        chmod +x ./.github/scripts/https.sh
        ./.github/scripts/https.sh legendsandmasters.nl


