name: Run JS Action
on: push
jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: https
        uses: ./
        with:
          url: 'upstreamservice.nl'
