on: push
name: Run Webpagetest
jobs:
  webPageTestActions:
    name: WebPageTestActions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: CoolZeroNL/cluster-check@master
        env:
          URL: https://example.com
