name: Run JS Action
on: push
jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: check https
      uses: .github/actions/https@master
      with:
        url: 'dd'
