name: ts-ts.legendsandmasters.nl
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Test URL
      run: |
        uname -a
        chmod +x ./.github/scripts/ts.sh
        ./.github/scripts/ts.sh ts.aalegendsandmasters.nl


